### ISSUE TITLE
Set up CI/CD pipeline

### ISSUE THREAD

**Issue by Markhauk** [Artx999/klinks#9]

**Comment by Markhauk** [comment]
Need to add a token for Expo in github actions secrets, but I don't have permission to do that in the settings(only owner has that permission).
https://docs.expo.dev/eas-update/github-actions/#publish-updates-on-push

**Comment by Artx999** [comment]
We have technically set up a pipeline already, but for now it only builds the application.

**Comment by Artx999** [comment]
Closing this issue, as we split it into different smaller issues.
Examples of this are #29 and #32.
